### ISSUE TITLE
Code for the document preprocessing part

### ISSUE THREAD

**Issue by Dr-Corgi** [truthless11/HyKnow#1]
Dear @truthless11 , I would like to know whether the code for the **document preprocessing** part, especially **the cumulative average TF-IDF (CA-TF-IDF)** in Appendix A, is available? Thank you very much.

**Comment by Silin159** [comment]
Dear @ruizhang1993 ,
Unfortunately, we did not keep the code for the data preprocessing, only final preprocessed dataset is available.
